name: Build stable branch images for Docker

on:
  push:
    branches:
      - 'stable/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_stable:
    if: github.repository == 'frrouting/frr'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Custom variables
        id: vars
        run: |
          # To package a specific git commit, the date of the commit gets
          # appended to the latest release, e.g. 1.0.0_git20180204.
          # This is the requirement by APKBUILD (abuild).
          # More details: https://wiki.alpinelinux.org/wiki/APKBUILD_Reference.
          echo ::set-output name=date::$(date +'%Y%m%d')
          # Get the real version specified in configure.ac file.
          echo ::set-output name=frr_version::$(grep AC_INIT configure.ac | cut -d '[' -f3 | cut -d ']' -f 1)

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/alpine/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frr:v${{ steps.vars.outputs.frr_version }}
          build-args: PKGVER=${{ steps.vars.outputs.date }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
